#
server.port=17560

server.servlet.encoding.charset=utf-8
server.servlet.encoding.enabled=true
server.compression.enabled=true
server.compression.mime-types=application/json, application/xml, text/html, text/plain, text/xml
spring.application.name=product-trading-service
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#spring.mvc.async.request-timeout=300000

#spring.datasource.url=jdbc:mysql://10.0.148.50:3306/app?characterEncoding=UTF-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#spring.datasource.username=crootuser
#spring.datasource.password=Crootuser.0
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:postgresql://172.20.101.1:5432/testdb?useUnicode=true&characterEncoding=utf8
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=3000

mybatis.mapper-locations=classpath*:/mapper/**Mapper.xml
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=1024MB

spring.redis.sentinel.nodes=172.20.101.45:26379,172.20.101.45:26380,172.20.101.45:26381
spring.redis.sentinel.master=mymaster_84
spring.redis.sentinel.password=qD4fnNQX3@AS1*Up
spring.redis.password=qD4fnNQX3@AS1*Up
spring.redis.database=3
spring.redis.lettuce.pool.max-idle=100
spring.redis.lettuce.pool.min-idle=0
spring.redis.lettuce.pool.max-active=300
spring.redis.lettuce.pool.max-wait=10000

logging.path=./
logging.file.path=./
logging.file.name=./ap-product-trading-service.log
logging.logback.rollingpolicy.max-file-size=1GB

merchant.scheduled.clear.time.scheduled=0 0 1 * * ?
